title:             Arkadiusz Kuczorski
email:             arkadiusz@kuczorski.pl
description:       Arkadiusz Kuczorski homepage
author:            Arkadiusz Kuczorski
baseurl:           "kuczorski.pl"
url:               "https://akuczorski.github.io"

# Social Profiles
twitter_username:  akuczorski
github_username:   akuczorski
facebook_username: arkadiusz.kuczorski
linkedin_isername: arkadiusz-kuczorski-7b70601

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
