title:             Arkadiusz Kuczorski
email:             arkadiusz@kuczorski.pl
description:       The main drivers behind cloud computing (r)evolution
author:            Arkadiusz Kuczorski
baseurl:           "/kuczorski.pl"
url:               "https://kuczorski.pl"

# Social Profiles
twitter_username:  akuczorski
github_username:   akuczorski
facebook_username: arkadiusz.kuczorski
linkedin_username: arkadiusz-kuczorski-7b70601

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Theme
# theme: jekyll-theme-awesome